version: "3.8"

networks:
  spark-airflow-network:
    external: true
    
services:
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    volumes:
      - /home/user/csv_data:/opt/data
      - /home/mahmoud1/jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"   # Spark master port
      - "8081:8080"   # Spark master web UI
    networks:
      - spark-airflow-network 
      
  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    volumes:
      - /home/user/csv_data:/opt/data
      - /home/mahmoud1/jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"   # Spark worker web UI
    networks:
      - spark-airflow-network 
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/user/work
      - /home/user/csv_data:/opt/data
      - /home/mahmoud1/jars/postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - spark-master
      - spark-worker
